window.PORTFOLIO_CONTENT = (() => {
  const projects = [
    {
      id: "repomesh",
      title: "RepoMesh",
      tagline: "多仓库 Coding Agent 协作与交付平台",
      category: "Agent Infra",
      year: "2026",
      question: "如何让多个 Coding Agent 在不同仓库中协作，同时约束修改范围并留下可验证的交付证据？",
      note: "代码写完，不应该意味着任务结束。",
      role: "核心架构设计主导｜Agent 运行框架负责人｜3 人团队",
      proof: "GOAI Agent Infra TOP 30｜31 Tasks · 4 Commits · 1 PR",
      summary: "围绕 Leader → Manager → Worker 层级协作、仓库画像、独立 Worktree、本地 Coding Agent 适配和人工审核点，跑通多仓任务从需求拆解到 PR 的纵向链路。",
      tags: ["Multi-Agent", "Context", "Worktree", "Diff", "AI Coding"],
      cover: { type: "image", src: "assets/project-covers/repomesh.png", tone: "indigo" },
      screens: [
        { src: "assets/project-covers/repomesh.png", caption: "Fig. 01｜Issue 视角下的多仓任务与状态" },
        { src: "assets/project-covers/repomesh-flow.png", caption: "Fig. 02｜从仓库扫描到需求判定的早期流程原型" },
      ],
      links: { github: "https://github.com/LBP97541135/GOAI-infra-repomesh" },
      problem: "文档型 Spec 的遵循与更新容易偏移；单个 Agent 难以处理多仓需求；AI Coding 过程缺少统一的审计、观测与人工介入机制。",
      decisions: [
        "使用 Leader → Manager → Worker 的上下级 Agent 关系管理跨仓目标、本仓 Task 与实际执行。",
        "项目建立时扫描各仓库 README 与依赖配置生成基础画像，由 Leader 判断关联度并与 Manager 核对。",
        "提供全自动、半自动和全部监督三种模式；半自动可选择仓库、Spec、Task、测试点、集成结果、PR、Diff 与任务分配等审核点。",
      ],
      architecture: [
        "Manager 拆分本仓 Task 时写入验收条件，测试 Agent 在隔离上下文中撰写脚本并完成验收。",
        "通过适配层在独立 Worktree 中调用本地 Coding Agent 应用。",
        "Spec 版本变化后重新评估影响范围，并把新 Task 与必要上下文重新分配给相关 Agent。",
      ],
      contribution: [
        "主导整体运行框架、身份管理、Context、初始化与 Coding Agent 适配层设计。",
        "主导信息可见性机制设计；该机制的具体实现由团队成员完成。",
        "参与三种监督模式、仓库核对、Spec 核对和跨仓变更同步机制设计。",
      ],
      validation: [
        "完成 31 个 Task、4 个 Commit 与 1 个 PR 的端到端实践。",
        "当前链路已覆盖 Task → Worktree → 改码 → 校验 → 测试 → Commit → PR。",
        "2026 GOAI 世界人工智能开源大赛 Agent Infra 赛道 TOP 30。",
      ],
      boundary: [
        "网站只陈述已设计与已跑通的链路，不把全部规划中的并发、门禁和分布式能力写成已完成。",
      ],
    },
    {
      id: "multiagent-werewolf",
      title: "AI 狼人杀",
      tagline: "Multi-Agent 博弈、评测与自进化系统",
      category: "Multi-Agent",
      year: "2026",
      question: "能否把 Agent 在博弈中的思考、发言影响和策略进化，变成一套可观测、可评测的系统？",
      note: "我想知道，一段发言到底改变了谁。",
      role: "核心架构设计主导｜评测与自进化负责人｜3 人团队",
      roleByPersona: {
        "ai-pm": "产品机制设计主导｜评测与自进化负责人｜3 人团队",
      },
      proof: "字节 AI 全栈挑战赛冠军｜A/B 平均 MVP 过程评分最高 +20.4%",
      summary: "以可玩狼人杀为载体，构建实时对局、信念矩阵、预投票意向、Vote Swing、模型对比和 PostGame Eval，并将高价值行为沉淀为 Prompt 与 Skill 优化。",
      tags: ["Belief Matrix", "Vote Swing", "PostGame Eval", "Prompt / Skill", "AgentScope"],
      cover: { type: "image", src: "assets/project-covers/multiagent-werewolf.png", tone: "crimson" },
      screens: [{ src: "assets/project-covers/multiagent-werewolf.png", caption: "Fig. 01｜多模型对局与观测入口" }],
      links: {
        github: "https://github.com/kissie-77/MultiAgent-Werewolf",
        demo: "labs/multiagent-werewolf/dist/",
        doc: "docs/projects/multiagent-werewolf.html",
      },
      problem: "普通多智能体演示往往只展示最终对话，看不到每次发言如何改变判断，也缺少稳定的赛后评测与迭代依据。",
      decisions: [
        "由 GameEngine 管理确定性规则、阶段状态和角色技能，AgentScope 负责 Agent 调用与协作。",
        "按身份向 Agent 分配可见事件与角色 Context，避免用提示词承担全部信息隔离责任。",
        "通过信息提取、分维度评分、综合汇总三阶段构建 PostGame Eval。",
      ],
      architecture: [
        "Belief Matrix 使用 B1 身份概率与 B2 他人对己怀疑度记录显式思考状态。",
        "讨论开始及每次发言后采集预投票意向快照，通过 Vote Swing、阵营收益与最终投票一致性量化发言影响。",
        "高价值行为进入 Prompt / Skill 优化流程，支持模型、策略和角色的横向对比。",
      ],
      contribution: [
        "主导 AgentScope + GameEngine 运行架构与信息可见性机制。",
        "全权设计并实现 Belief Matrix、预投票意向快照和 Vote Swing。",
        "负责 PostGame Eval、Prompt / Skill 管理与自进化实验。",
      ],
      validation: [
        "2026 字节跳动 AI 全栈挑战赛冠军。",
        "覆盖 12 种模型与 20 局演化实验。",
        "对比旧版 Prompt / Skill，A/B 实验平均 MVP 过程评分最高提升 20.4%。",
      ],
      boundary: ["不再使用缺少统一依据的“60 → 80”旧指标。"],
    },
    {
      id: "undercover",
      title: "谁是卧底",
      tagline: "确定性 Harness 下的真人 × 多模型博弈",
      category: "Agent Harness",
      year: "2026",
      question: "如果三个真实模型只能看到自己的词牌，它们真的能学会隐瞒、怀疑、投票和恢复一整局游戏吗？",
      note: "模型可以提议行动，但不能自己决定游戏规则。",
      role: "独立设计与开发",
      proof: "156/156 自动化用例｜10/10 Desktop + Mobile E2E",
      summary: "使用服务端权威状态机、最小白名单 Context、Strict Schema、SQLite 事务、Revision 防旧写和 SSE 安全帧，完成一名人类与 DeepSeek、豆包、千问的整局博弈。",
      tags: ["State Machine", "Context Projection", "Schema", "Recovery", "SSE"],
      cover: { type: "image", src: "assets/project-covers/undercover-game.png", tone: "teal" },
      screens: [
        { src: "assets/project-covers/undercover-game.png", caption: "Fig. 01｜真实对局观战：多个模型玩家共享规则，私有词牌互相隔离" },
        { src: "assets/project-covers/undercover-home.png", caption: "Fig. 02｜开局入口：经典 / 猜词模式与词语难度选择" },
      ],
      links: { github: "https://github.com/LBP97541135/sheishiwodi" },
      problem: "模型不能直接决定规则、胜负和可见信息；真实模型还会出现格式错误、超时、过期结果和隐私泄漏，需要由 Harness 承担可靠性。",
      decisions: [
        "服务端状态机是唯一裁判，模型只提交结构化行动提案。",
        "AgentInputProjector 构造最小白名单 Context，不向浏览器、REST、SSE 或其他 Agent 暴露私有信息。",
        "默认假模型承担确定性回归，真实模型必须通过显式命令单独验收。",
      ],
      architecture: [
        "共享纯状态机管理准备、描述、秘密投票、平票辩解、重投、淘汰和终局。",
        "SQLite 同一事务写入快照、不可变事件、私有动作、安全帧和幂等命令结果。",
        "Revision 绑定、有限重试、格式修复、恢复和 SSE 游标补发共同处理模型与网络不稳定。",
      ],
      contribution: ["独立完成产品范围、架构、前后端、测试体系、真实模型验收与发布文档。"],
      validation: [
        "Shared + Server + Web Vitest 156/156 通过。",
        "Playwright E2E 10/10 通过，覆盖 Desktop Chrome 与 Pixel 5。",
        "3 个角色 × 2 类动作的 6 次真实模型调用通过结构、合法目标与信息隔离校验。",
      ],
      boundary: ["真实模型完成过复用同一状态机的整局验证；HTTP + SQLite 的真实付费全栈 E2E 仍未完成。"],
    },
    {
      id: "haji-ai",
      title: "Haji AI",
      tagline: "本地优先的 AI 社交与 Multi-Agent 框架",
      category: "Multi-Agent",
      year: "2026",
      question: "如果 AI 角色有长期记忆、表达意愿和关系网络，朋友圈会不会成为比聊天框更自然的 AI 社交界面？",
      note: "我不想再做一个只有聊天框的 AI 产品。",
      role: "独立设计与开发",
      proof: "15 个核心模块｜574 项测试通过",
      summary: "从零搭建 Python Multi-Agent 框架，覆盖 Skill 检索、JSON / JSONL Memory、AST 受限执行、主动触发和意愿驱动群聊，并完成 AI 社交产品闭环。",
      tags: ["Memory", "Skill Retrieval", "AST Sandbox", "Agent Loop", "Local-first"],
      cover: { type: "image", src: "assets/project-covers/haji-ai.png", tone: "violet" },
      screens: [{ src: "assets/project-covers/haji-ai.png", caption: "Fig. 01｜让消息、朋友圈、记忆和主动表达出现在同一个产品里" }],
      links: {
        github: "https://github.com/LBP97541135/haji-ai",
        demo: "labs/haji-ai/",
        doc: "docs/projects/haji-ai.html",
      },
      problem: "只使用聊天窗口难以展示角色关系、社区氛围、主动表达和长期内容价值。",
      decisions: [
        "不依赖 LangChain、FAISS 和 NumPy，使用纯 Python 实现核心框架与向量相似度。",
        "Memory 使用 JSON / JSONL 持久化，保证重启后恢复会话与群聊历史。",
        "AST 静态分析与受限执行环境共同约束代码工具。",
      ],
      architecture: ["支持 DIRECT、REACT、PLAN_AND_EXECUTE 三种执行模式和多类主动触发。"],
      contribution: ["独立完成 Agent 框架、后端服务、社交产品前端与测试。"],
      validation: ["15 个核心模块，574 项测试通过。"],
      boundary: ["重点展示框架与社交闭环，不把所有内部模块同时堆进首页。"],
    },
    {
      id: "work-order-agent",
      title: "商家工单助手",
      tagline: "Router Agent + 领域 Agent 的线上工单自动化",
      category: "企业 Agent",
      year: "2026",
      question: "如何在写操作风险可控的前提下，把高频商家入驻工单从人工分流变成 Agent 自动处理？",
      note: "先让 Agent 会判断，再决定哪些操作值得自动化。",
      role: "独立设计与开发",
      proof: "3 天 96 张真实工单｜50% 自动闭环｜11h → 4h",
      summary: "优先选择工单量最大的商家入驻场景，通过 Router Agent 识别意图与实体，领域 Agent 按 SOP Skill 调用 RPC Tool，并按风险进入自动闭环、人工复核或转人工。",
      tags: ["Router Agent", "SOP Skill", "RPC Tool", "Human-in-the-Loop"],
      cover: { type: "system", label: "ROUTE / SKILL / RPC", tone: "orange" },
      problem: "商家入驻工单量大、判断链路长，人工需要跨系统查询和操作，端到端等待时间长。",
      decisions: [
        "先做工单量最大的商家入驻域，再通过 Router 与领域能力解耦支持开发平台、店铺资质等后续分类。",
        "把取消入驻、资质审核解冻等标准操作沉淀为 SOP Skill。",
        "写操作根据风险进入自动闭环、人工复核或转人工。",
      ],
      architecture: ["Router 产出业务域、关键实体和目标操作；领域 Agent 选择 Skill 并调用 RPC Tool。"],
      contribution: ["独立完成两级 Agent 架构、典型 SOP Skill、RPC Tool 调用和处理分流机制。"],
      validation: [
        "上线 3 天处理 96 张真实线上工单。",
        "50% 自动闭环，20% 仅需人工复核。",
        "Agent 单次处理约 1–2 分钟，端到端平均时长由 11 小时降至 4 小时。",
      ],
      boundary: ["端到端时长包含人工排队与确认等待，不把全部缩短归因于模型推理速度。"],
    },
    {
      id: "data-collection-platform",
      title: "Agent 数据采集平台",
      tagline: "从逐次人工爬取到可复用的采集工作流",
      category: "AI 产品",
      year: "2026",
      question: "能否把每次都依赖开发人工爬取、整理和交付的数据需求，变成产品组可以直接使用的平台？",
      note: "第一次试样并不准，所以才需要反馈闭环。",
      role: "产品设计 + TypeScript MVP｜独立开发",
      proof: "8 平台调研｜小红书 + 抖音 MVP｜5 次真实任务",
      summary: "调研算法组和市场组的多类采集需求，从成本、效率、可控性与操作门槛完成选型；使用 TikHub + Agent 跑通需求理解、接口发现、试采样、反馈修正与正式交付。",
      tags: ["User Research", "MVP", "MCP", "TikHub", "Feedback Loop"],
      cover: { type: "image", src: "assets/project-covers/data-collection-platform.png", tone: "emerald" },
      screens: [
        { src: "assets/project-covers/data-collection-platform.png", caption: "Fig. 01｜需求理解、接口探索与动态交付的三阶段设计" },
        { src: "assets/project-covers/data-collection-task-flow.png", caption: "Fig. 02｜从平台用户发起任务到追加采集的完整流程" },
      ],
      problem: "旧流程由需求方提需求，开发逐次人工爬取和整理后交付；每次都要重新处理，没有统一平台和可复用执行计划。",
      decisions: [
        "调研 8 个平台的多类需求，从成本、效率、采集可控性和操作简易程度比较方案。",
        "选择 TikHub + Agent，并以需求量最大、可快速接入的小红书和抖音作为 MVP 优先平台。",
        "试采样暴露筛选偏差后，新增样本级 AI 反馈，而不是直接进入大规模采集。",
      ],
      architecture: [
        "主 Agent 理解需求；平台 Agent 通过 MCP 动态发现并验证接口；已验证链路转成可重复执行的采集计划。",
        "支持试采样、分页验证、字段增删改名、CSV / 媒体交付。",
        "用户可批量标记不喜欢的样本和原因，AI 更新需求文档后重新试采样。",
      ],
      contribution: ["独立交付调研报告、PRD、交互原型和 TypeScript 全栈 MVP。"],
      validation: ["产品组内部试用并完成 5 次真实任务；MVP 45 项测试通过。"],
      boundary: ["仍处于内部试用和平台交互研究扩展阶段。"],
    },
    {
      id: "member-lottery",
      title: "会员抽奖活动",
      tagline: "活动前后台产品设计与真实上线",
      category: "产品上线",
      year: "2026",
      question: "如何把可见人群、会员资格、活动周期、库存和发奖风险统一沉淀为可配置的活动系统？",
      note: "活动上线以后，哪些东西不能再改，比能配置什么更重要。",
      role: "前后台产品设计与上线验收",
      proof: "8 月 6 日上线｜累计访问 1万+｜抽奖参与率 90%+",
      summary: "负责周年庆会员抽奖从业务规则、后台配置、前台交互到上线验收的完整方案，并将发布后禁改、状态锁定和重复发奖防护固化到产品规则中。",
      tags: ["PRD", "Prototype", "Lifecycle", "Inventory", "Analytics"],
      cover: { type: "image", src: "assets/project-covers/member-lottery.png", tone: "red" },
      screens: [{ src: "assets/project-covers/member-lottery.png", caption: "Fig. 01｜活动主页面与中奖结果设计" }],
      problem: "活动需要同时约束可见人群、会员等级、预热期和活动期、奖品库存、概率、次数与中奖记录，且上线后部分配置不能继续修改。",
      decisions: [
        "将活动类型、可见人群、预热期 / 活动期与会员等级限制纳入发布后禁改或上线后锁定规则。",
        "统一设计库存、概率、抽奖次数、中奖记录和重复发奖防护。",
        "定义活动埋点与上线验收口径。",
      ],
      architecture: ["后台配置状态与前台活动状态保持一致，用户可在活动页查看奖品详情与中奖信息。"],
      contribution: ["负责调研、PRD、后台原型、前台活动 Demo、交互规则和上线验收。"],
      validation: ["活动于 2026 年 8 月 6 日上线；累计访问人数 1 万+；抽奖参与率 90%+。"],
      boundary: ["网站使用公开活动页和本人原型，不展示内部真实用户数据。"],
    },
    {
      id: "ship-agent",
      title: "船舶运货助手",
      tagline: "Workflow + RAG + Python 的生产业务助手",
      category: "企业 Agent",
      year: "2025",
      question: "在弱模型条件下，如何稳定完成线路检索、载重计算和结构化报告生成？",
      note: "模型不够强时，先把每一步变得足够简单。",
      role: "方案设计与交付｜独立负责",
      proof: "100 条真实案例通过 98 条｜约 1分20秒｜每周 1万+ 请求",
      summary: "将复杂请求拆成信息抽取、线路规划和确定性计算三阶段，使用清洗后的历史订单构建 RAG，Python Tool 负责载重与费用计算，并按模板生成报告。",
      tags: ["Workflow", "RAG", "Python Tool", "Human Acceptance"],
      cover: { type: "system", label: "ROUTE / LOAD / REPORT", tone: "blue" },
      problem: "人工需要整理历史订单、必要时查阅路线图，再完成大量线路规划、载重核算和报告整理。",
      decisions: [
        "将复杂请求拆成信息抽取、线路规划和数值计算，降低每一步对模型能力的要求。",
        "历史订单经排序、去重、规范化后，按相同起始地分组切片。",
        "使用增量更新；删除时按起始地快速定位已有切片。",
      ],
      architecture: ["RAG 检索相似历史线路；Python Tool 完成载重与费用计算；模板生成结构化 Markdown 报告。"],
      contribution: ["独立完成需求梳理、Workflow、RAG 数据组织、Python Tool 与交付验收。"],
      validation: [
        "100 条客户真实历史案例人工验收通过 98 条。",
        "单次端到端响应约 1 分 20 秒。",
        "上线后每周稳定处理 1 万+ 请求。",
      ],
      boundary: ["98/100 是人工验收结果，不写成无条件的 98% 模型准确率。"],
    },
    {
      id: "aigc-test-image",
      title: "测品图生图评测体系",
      tagline: "双层视觉评测与标杆素材建设",
      category: "Agent Eval",
      year: "2026",
      question: "如何把模糊的图片合规判断变成可复用的标杆库、评测维度与自动化筛选流程？",
      note: "评测不是最后打分，它会反过来决定生成方向。",
      role: "评测方案与标杆库建设",
      proof: "20,000 张候选｜6,700+ 标杆｜违规率 11% → 1.7%",
      summary: "从两万张测品图中建立筛选标准与标杆素材库，使用小模型快速初筛、大模型细粒度评分，并将人脸与光影风险纳入评测维度。",
      tags: ["Visual Eval", "Dataset", "Judge", "Quality Metric"],
      cover: { type: "system", label: "FILTER / SCORE / BENCHMARK", tone: "rose" },
      problem: "AI 生图缺少稳定的参考素材与评测维度，人脸和光影处理容易触发平台违规。",
      decisions: ["小模型承担高速初筛，大模型只对候选图进行多维评分，以平衡成本与精度。"],
      architecture: ["构图、人脸质量、光影和服装清晰度等维度共同构成标杆筛选与生成评测标准。"],
      contribution: ["负责筛选标准、标杆素材库、双层评测流程和 Prompt 设计。"],
      validation: ["6,700+ 标杆素材入库；AI 生图违规率由 11% 降至 1.7%。"],
      boundary: ["企业内部图片不作为网站公开素材。"],
    },
    {
      id: "evo-murder-game",
      title: "进化酒馆",
      tagline: "多人协作的 Agent 自进化剧本杀",
      category: "Product Experiment",
      year: "2026",
      question: "如果 AI 角色能在对局后复盘行为，并把有效策略沉淀为可复用经验，单人剧本杀会不会越玩越懂你？",
      note: "我们想让复盘不只是一张结算页。",
      role: "核心 Agent 与后端链路贡献｜4 人协作",
      proof: "EvoMap 黑客松最佳人气奖｜个人 38 个可追溯提交",
      summary: "围绕单人剧本杀、流式 Agent 对话、证物与公共讨论、复盘和 Gene/Capsule 经验沉淀完成多人协作产品实验。",
      tags: ["Game Engine", "Streaming", "Evidence", "Gene / Capsule"],
      cover: { type: "image", src: "assets/project-covers/evo-murder-game.png", tone: "gold" },
      screens: [{ src: "assets/project-covers/evo-murder-game.png", caption: "Fig. 01｜多人协作完成的单人剧本杀产品入口" }],
      links: {
        github: "https://github.com/LBP97541135/evo-murder-game",
        team: "https://github.com/Janbecca/AI-Murder-Mystery-Game",
        demo: "labs/evo-murder-game/",
        doc: "docs/projects/evo-murder-game.html",
      },
      problem: "传统剧本杀依赖组局与真人 DM，单人用户很难随时进入有角色差异、证物推理和复盘反馈的完整体验。",
      decisions: ["以 Agent 承担角色对话、证物响应与赛后反思，并把经验沉淀为 Gene / Capsule。"],
      architecture: ["项目经历多轮重构，当前网站只陈述可由主分支和提交历史验证的链路。"],
      contribution: [
        "负责项目骨架与模块化后端、游戏引擎与持久化、流式 Agent 调用。",
        "负责公共讨论与证物链路、复盘及 Gene/Capsule 自进化链路。",
        "后续参与后端重构与本地游戏流程稳定。",
      ],
      validation: ["完整历史仓 119 个提交；本人以两个作者身份贡献 38 个提交；获得 EvoMap 黑客松最佳人气奖。"],
      boundary: ["项目经历过多轮重构，网站只保留当前主分支与个人提交历史能够验证的能力。"],
    },
    {
      id: "career-assistant",
      title: "AI for Career",
      tagline: "HarmonyOS 端侧职业成长助手",
      category: "Product Experiment",
      year: "2026",
      question: "能不能在手机端把一份简历逐步变成可解释的能力画像，并通过 AI 追问补齐证据？",
      note: "简历不该只是文本，它应该能回到具体证据。",
      role: "核心功能与架构贡献｜持续开发中",
      proof: "ArkTS Debug 构建通过｜16 个核心行为用例",
      summary: "探索简历 / JD 解析、AI 追问、BYOK、OCR、本地 RDB 与能力评分在 HarmonyOS 端的完整体验。",
      tags: ["HarmonyOS", "ArkTS", "OCR", "BYOK", "RDB"],
      cover: { type: "image", src: "assets/project-covers/career-assistant.png", tone: "cyan" },
      screens: [{ src: "assets/project-covers/career-assistant.png", caption: "Fig. 01｜从上传简历到能力画像与岗位匹配" }],
      links: { github: "https://github.com/LBP97541135/CareerAssistant" },
      problem: "求职资料与能力证据分散，用户很难从简历文本持续沉淀可解释的职业能力画像。",
      decisions: ["采用端侧优先架构，使用 DAO 隔离页面与本地 RDB，为后续云端迁移保留边界。"],
      architecture: ["覆盖文档选择、OCR、AI 配置、简历解析、追问补写与能力评分。"],
      contribution: ["负责简历上传、AI 追问、通用 UI、DAO / 错误链、能力评分、AI Gateway 与配置。"],
      validation: ["ArkTS Debug 构建和 unsigned HAP 产出通过；16 个核心行为用例通过。"],
      boundary: ["正式签名、真机、真实 AI 网络和设备交互验收仍在推进。"],
    },
    {
      id: "chart-mcp",
      title: "Chart MCP",
      tagline: "私有化图表生成服务的工程适配",
      category: "Developer Tool",
      year: "2025",
      question: "如果 AI 能直接调用私有图表服务，业务数据是否可以在不离开环境的前提下完成可视化？",
      note: "图表能力可以复用，但数据不一定要离开自己的环境。",
      role: "基于 AntV 开源项目的工程适配与部署",
      proof: "40+ 图表｜stdio + SSE｜缓存与并发队列",
      summary: "基于 AntV MCP Server 完成服务端渲染、私有部署、指纹缓存、并发队列与中文字体适配。",
      tags: ["MCP", "AntV", "SSR", "Cache", "Private Deploy"],
      cover: { type: "system", label: "MCP / CHART / PRIVATE", tone: "blue" },
      links: { github: "https://github.com/LBP97541135/mcp-chart" },
      problem: "图表生成经常需要处理财务、客户和内部指标，不能把数据交给不受控的外部服务。",
      decisions: ["复用 AntV MCP Server 的图表能力，重点完成私有部署与运行稳定性适配。"],
      architecture: ["支持 stdio 与 SSE；使用服务端渲染、请求指纹缓存和并发队列。"],
      contribution: ["负责缓存、并发、中文字体和私有化部署相关适配。"],
      validation: ["可生成 40+ 图表类型并部署为私有服务。"],
      boundary: ["不再表述为从零手写 MCP 协议，也不声称当前实现支持三种传输。"],
    },
    {
      id: "ai-work-coach",
      title: "AI Work Coach",
      tagline: "本地优先的自适应职业学习 Agent",
      category: "Product Experiment",
      year: "2026",
      question: "如何把日常训练、AI 批改和能力画像连接成一个可解释的成长闭环？",
      note: "我需要的不是题库，而是一套会跟着我变化的训练。",
      role: "独立设计与开发",
      proof: "训练 → 批改 → 画像更新闭环｜36 个测试",
      summary: "围绕每日训练、任务追踪、AI 教练、历史复盘与能力画像完成本地优先的成长工具。",
      tags: ["Adaptive Learning", "Profile", "Local-first"],
      cover: { type: "image", src: "assets/project-covers/ai-work-coach.png", tone: "lime" },
      screens: [{ src: "assets/project-covers/ai-work-coach.png", caption: "Fig. 01｜训练、批改、目标与画像更新的同一工作台" }],
      links: {
        github: "https://github.com/LBP97541135/ai-work-coach",
        demo: "labs/ai-work-coach/",
        doc: "docs/projects/ai-work-coach.html",
      },
      problem: "职场反馈碎片化，用户很难把一次次任务经历转化为持续成长路径。",
      decisions: ["使用显式推荐公式与画像更新权重，使 AI 推荐和能力变化可解释。"],
      architecture: ["课程生成、作答、批改、画像更新与历史复盘形成闭环。"],
      contribution: ["独立完成产品、前后端和测试。"],
      validation: ["36 个测试用例覆盖核心闭环。"],
      boundary: ["资料源为静态资料，不描述为联网搜索。"],
    },
    {
      id: "invoice-agent",
      title: "发票报销 Agent",
      tagline: "税务核验与多维表联动",
      category: "Enterprise Experiment",
      year: "2025",
      question: "能否用 Agent 串联发票真伪、重复报销和财务台账核验？",
      note: "在财务流程里，自动化首先要回答的是怎么避免重复。",
      role: "独立方案与开发",
      proof: "重复报销拦截率 100%",
      summary: "接入税务核验能力，并用多维表完成预录入、发票记录、报销状态与财务台账联动。",
      tags: ["API", "Verification", "Workflow"],
      cover: { type: "system", label: "INVOICE / CHECK / LEDGER", tone: "slate" },
      problem: "人工查验真伪与重复报销成本高，多表状态容易不一致。",
      decisions: ["使用预录入基准和多维交叉核验，异常进入人工处理。"],
      architecture: ["税务核验、字段比对、重复检查和台账写入串成自动流程。"],
      contribution: ["独立完成接口、核验逻辑、表结构与看板。"],
      validation: ["测试数据中重复报销拦截率 100%。"],
      boundary: ["作为 Playground 展示，不在首页冒充大规模生产指标。"],
    },
    {
      id: "material-agent",
      title: "物资管理 Agent",
      tagline: "自然语言驱动的企微物资流程",
      category: "Enterprise Experiment",
      year: "2025",
      question: "自然语言能否替代复杂表单，完成物资进出、换位和告警？",
      note: "自然语言只是入口，真正重要的是后面的确定性写入。",
      role: "独立方案与开发",
      proof: "效率提升 18×｜上架企微官方市场",
      summary: "基于企微 API 和多维表实现物资入库、出库、位置变更与库存告警。",
      tags: ["WeCom", "Workflow", "Multi-table"],
      cover: { type: "system", label: "STOCK / MOVE / ALERT", tone: "amber" },
      problem: "传统物资流程步骤多、培训成本高，跨表操作容易漏记。",
      decisions: ["使用自然语言解析操作，再由确定性工具完成多表写入。"],
      architecture: ["意图解析、数据校验、多表写入和告警通知形成闭环。"],
      contribution: ["独立完成流程、数据结构、Prompt 和应用上架。"],
      validation: ["操作效率提升 18 倍，并上架企微官方市场。"],
      boundary: [],
    },
    {
      id: "her-catalyst",
      title: "HER 催化剂定向生成",
      tagline: "EGNN + 扩散模型的材料生成实验",
      category: "AI for Science",
      year: "2025",
      question: "能否用物理等变约束，让扩散模型生成结构合理的二维催化材料候选？",
      note: "生成一个好看的结构不难，生成一个物理上说得通的结构才难。",
      role: "个人科研实验",
      proof: "EGNN｜多目标引导扩散",
      summary: "探索等变图神经网络、扩散生成与多目标性质引导在二维析氢催化材料中的应用。",
      tags: ["EGNN", "Diffusion", "Materials"],
      cover: { type: "system", label: "ATOM / EQUIVARIANT / DIFFUSION", tone: "purple" },
      links: { github: "https://github.com/LBP97541135/her-catalyst-diffusion" },
      problem: "传统实验筛选材料周期长，生成模型还必须满足结构对称与物理约束。",
      decisions: ["使用 EGNN 保持旋转和平移等变性，并用多任务目标引导扩散过程。"],
      architecture: ["原子图表示、等变去噪和性质目标共同构成生成流程。"],
      contribution: ["独立完成模型实验与代码。"],
      validation: ["展示结构生成与性质优化实验，不使用缺乏可复现实验支撑的合成成功率。"],
      boundary: ["不声称已完成真实实验合成验证。"],
    },
    {
      id: "community-agent",
      title: "社里办",
      tagline: "高校社团 Multi-Agent 协作系统",
      category: "Product Experiment",
      year: "2025",
      question: "社团流程、历史知识和活动创意能否由多个 Agent 分工协作？",
      note: "我第一次认真思考：多个 Agent 到底应该怎么分工。",
      role: "AI 产品与 Multi-Agent 方案",
      proof: "30+ 工作流｜4 个知识库｜省赛二等奖",
      summary: "在钉钉 DEAP 上用主 Agent 调度内部管理、团队建设和活动创新 Agent。",
      tags: ["Multi-Agent", "Workflow", "Knowledge Base"],
      cover: { type: "system", label: "CLUB / KNOWLEDGE / FLOW", tone: "green" },
      problem: "学生社团流程繁琐、经验难以传承、活动创新依赖少数成员。",
      decisions: ["按内部管理、团队建设和活动创新拆分 Agent 与知识库。"],
      architecture: ["主 Agent 路由请求，专业 Agent 调用工作流和知识库。"],
      contribution: ["负责产品方案、Multi-Agent 架构、工作流与知识库。"],
      validation: ["浙江省人工智能竞赛二等奖，省前 15%。"],
      boundary: [],
    },
    {
      id: "money-printer-turbo",
      title: "MoneyPrinterTurbo",
      tagline: "短视频生成工具的本地化探索",
      category: "Open-source Study",
      year: "2026",
      question: "能否把短视频生产中的关键词、素材和文案配置压缩成更短的输入流程？",
      note: "开源项目最适合拿来验证一个更短的用户路径。",
      role: "开源项目使用与提示词实验",
      proof: "主题 → 关键词 → 素材 → 文案",
      summary: "基于开源项目进行本地化使用与 Prompt 流程实验，不作为核心个人工程成果。",
      tags: ["Prompt", "Video", "Open Source"],
      cover: { type: "image", src: "assets/project-covers/money-printer-turbo.png", tone: "pink" },
      screens: [{ src: "assets/project-covers/money-printer-turbo.png", caption: "Fig. 01｜把主题、素材与成片参数放进同一控制台" }],
      links: { demo: "labs/money-printer-turbo/", doc: "docs/projects/money-printer-turbo.html" },
      problem: "短视频生成配置链路较长，普通用户需要反复切换素材和文案设置。",
      decisions: ["使用关键词扩写桥接主题输入与素材检索。"],
      architecture: ["主题、关键词、素材和文案串成单一流程。"],
      contribution: ["完成本地部署、提示词实验与展示页面。"],
      validation: ["仅作为开源学习和产品探索展示。"],
      boundary: ["不把上游项目能力描述为个人独立开发。"],
    },
  ];

  const experiences = {
    xiaohongshu: {
      company: "小红书",
      role: "产品工程师",
      time: "2026.03 – 2026.06",
      metrics: ["96 张真实线上工单", "11h → 4h", "50% 自动闭环"],
      related: ["work-order-agent", "aigc-test-image"],
      focus: {
        "agent-dev": "在商家技术组独立开发工单 Agent，负责 Router Agent、领域 Agent、SOP Skill 与 RPC Tool，推动真实线上工单处理。",
        "ai-pm": "从工单结构中选择量最大的商家入驻作为 MVP，设计自动闭环、人工复核和转人工机制，并为后续领域扩展预留结构。",
        "agent-qa": "围绕写操作风险、人工确认、结果回查和真实线上数据验证 Agent 处理质量，区分模型执行时间与人工排队时间。",
      },
    },
    yanhun: {
      company: "炎魂网络科技",
      role: "产品经理",
      time: "2026.07 – 至今",
      metrics: ["累计访问 1万+", "抽奖参与率 90%+", "5 次真实采集任务"],
      related: ["data-collection-platform", "member-lottery"],
      focus: {
        "agent-dev": "负责内部 Agent 数据采集平台的方案与 TypeScript MVP，并完成会员抽奖前后台规则、原型和上线验收。",
        "ai-pm": "从调研、选型、PRD、原型与 MVP 推进到内部试用或真实上线，覆盖 Agent 数据采集平台与会员抽奖活动。",
        "agent-qa": "在数据采集试样中引入 AI 反馈闭环，并为会员抽奖定义发布后禁改、状态锁定、重复发奖防护与上线验收口径。",
      },
    },
    huanjie: {
      company: "珠海环界云计算",
      role: "AI 解决方案工程师",
      time: "2025.11 – 2026.02",
      metrics: ["每周 1万+ 请求", "100 条案例通过 98 条", "约 1分20秒 / 次"],
      related: ["ship-agent", "invoice-agent", "material-agent"],
      focus: {
        "agent-dev": "独立完成客户 Agent 的需求拆解、Workflow、RAG、Python Tool 与结构化报告交付。",
        "ai-pm": "直接对客完成需求调研、方案设计、工作流搭建和上线验收，将跨行业诉求翻译为可用的 AI 方案。",
        "agent-qa": "使用真实历史案例进行人工验收，将数值计算从模型中剥离，并通过固定模板与回归样本控制交付质量。",
      },
    },
  };

  const personas = {
    "agent-dev": {
      label: "Agent 应用开发",
      short: "应用开发",
      en: "AGENT ENGINEER",
      role: "Agent 应用开发工程师",
      headline: "从 Agent 运行机制，\n到真实业务交付",
      summary: "围绕 Context、Tool Use、Multi-Agent 与质量验证，完成过企业 Agent、自研框架和多仓 Coding Agent 项目。",
      experienceOrder: ["xiaohongshu", "huanjie", "yanhun"],
      companyLine: ["小红书 · 产品工程师", "环界云 · AI 解决方案工程师", "炎魂 · 产品经理"],
      proofs: [
        { label: "字节 AI 全栈挑战赛", value: "冠军", note: "Multi-Agent 博弈与评测" },
        { label: "GOAI Agent Infra", value: "TOP 30", note: "多仓 Coding Agent" },
        { label: "真实业务实践", value: "3 段", note: "电商 · 企业 Agent · 游戏产品" },
      ],
      selected: ["repomesh", "multiagent-werewolf", "undercover", "haji-ai", "work-order-agent"],
      projectTitle: "让 Agent 从能运行，走向可交付",
      projectIntro: "这些案例承接简历中的核心能力：运行框架、信息边界、工具执行、多智能体协作与真实业务交付。",
      capabilityTitle: "我如何把 Agent 做成系统",
      capabilities: [
        { title: "Context 与信息边界", summary: "让每个 Agent 只看到完成任务所需的信息。", detail: "通过身份投影、角色 Context、系统分配可见性与最小白名单降低信息泄漏和上下文噪声。", projects: ["undercover", "multiagent-werewolf", "repomesh"] },
        { title: "Tool Use 与业务执行", summary: "把 Agent 判断连接到可控的真实操作。", detail: "将 SOP 封装为 Skill，通过 RPC / Python Tool 完成确定性执行，并按风险配置人工确认。", projects: ["work-order-agent", "ship-agent"] },
        { title: "Multi-Agent 编排", summary: "为不同责任设计清晰的协作关系。", detail: "实践 Router → Domain Agent、Leader → Manager → Worker 和 GameEngine → Agent 等多种协作结构。", projects: ["repomesh", "multiagent-werewolf", "work-order-agent"] },
        { title: "状态、记忆与恢复", summary: "让 Agent 在刷新、重启和异常后仍能继续。", detail: "覆盖状态机、持久化、Revision 防旧写、幂等恢复与 JSON / JSONL Memory。", projects: ["undercover", "haji-ai"] },
        { title: "Eval 与可观测", summary: "用 Trace 和指标解释 Agent 为什么成功或失败。", detail: "从思考、投票与工具调用中提取过程信号，建立 PostGame Eval、回放和回归证据。", projects: ["multiagent-werewolf", "undercover"] },
        { title: "工程交付", summary: "把代码、测试、部署和验收串成完成标准。", detail: "覆盖 Python / TypeScript 后端、Git、自动化测试、E2E、Worktree 与生产交付。", projects: ["repomesh", "undercover", "work-order-agent"] },
      ],
      skills: [
        ["Agent 工程", "Context、Tool Use、Structured Output、Multi-Agent、Memory、Workflow、Human-in-the-Loop"],
        ["评测与可观测", "Evals、Trace、Regression、Observability、Prompt / Skill 版本管理"],
        ["检索与协议", "RAG、MCP、HTTP/RPC、SSE、WebSocket"],
        ["工程技术", "Python、TypeScript、Java、FastAPI、SQL、Git、Docker、Pytest、Playwright"],
        ["框架平台", "AgentScope、FastGPT、Darwin、Langflow"],
      ],
      primaryCta: "查看精选案例",
      heroNote: "我喜欢先把系统跑起来，再追问它为什么可靠。",
      contactTitle: "一起把 Agent 做成可靠的系统",
      resume: "assets/resumes/吕祎晗-Agent应用开发工程师.pdf",
    },
    "ai-pm": {
      label: "AI 技术产品",
      short: "技术产品",
      en: "AI PRODUCT",
      role: "AI 技术产品经理",
      headline: "从真实问题，\n到可验证的 AI 产品",
      summary: "具备从用户调研、优先级判断、PRD 与原型设计，到 TypeScript MVP 开发、上线验证和反馈迭代的完整实践。",
      experienceOrder: ["yanhun", "xiaohongshu", "huanjie"],
      companyLine: ["炎魂 · 产品经理", "小红书 · 产品工程师", "环界云 · AI 解决方案工程师"],
      proofs: [
        { label: "真实产品上线", value: "1万+ / 90%+", note: "累计访问 / 抽奖参与率" },
        { label: "独立全栈验证", value: "小红书 + 抖音", note: "Agent 数据采集 MVP" },
        { label: "业务流程提效", value: "11h → 4h", note: "商家工单端到端时长" },
      ],
      selected: ["data-collection-platform", "member-lottery", "work-order-agent", "ship-agent"],
      projectTitle: "把真实问题，做成可验证的 AI 产品",
      projectIntro: "从需求优先级、方案选型、原型与 MVP，到真实试用和上线数据，展示完整的产品判断与交付链路。",
      capabilityTitle: "我如何定义并验证 AI 产品",
      capabilities: [
        { title: "用户问题与优先级", summary: "先判断问题是否值得用 AI，再决定做什么。", detail: "结合用户访谈、业务频次、失败成本、接入成本与可控性选择 MVP 场景。", projects: ["data-collection-platform", "work-order-agent"] },
        { title: "MVP 范围与验证", summary: "用最短链路验证最关键的产品假设。", detail: "主动控制验证成本，使用原型、TypeScript MVP、试采样与真实任务逐步验证。", projects: ["data-collection-platform", "member-lottery"] },
        { title: "Agent 方案设计", summary: "把模糊需求拆成角色、任务、工具和反馈。", detail: "理解模型边界，选择 Router / Domain Agent、Workflow、RAG、Tool 与人工审核的组合。", projects: ["work-order-agent", "ship-agent"] },
        { title: "数据与反馈闭环", summary: "上线不是结束，反馈必须回到下一轮方案。", detail: "通过埋点、试样反馈、错误原因与人工验收判断产品是否有效。", projects: ["member-lottery", "data-collection-platform"] },
        { title: "项目推动与验收", summary: "覆盖需求、设计、研发对齐、上线和验收。", detail: "有内部工具、公开活动和直接对客交付经验，能够把需求推进到真实使用。", projects: ["member-lottery", "ship-agent"] },
        { title: "技术判断力", summary: "知道 Agent 能做什么，也知道哪里需要确定性系统。", detail: "能够在模型、规则流程、代码工具、RAG 与人工确认之间做边界判断。", projects: ["work-order-agent", "data-collection-platform", "ship-agent"] },
      ],
      skills: [
        ["产品能力", "用户调研、需求分析、优先级判断、PRD、原型设计、MVP、埋点与验收"],
        ["Agent 产品", "Context、Tool Use、Multi-Agent、RAG、MCP、Workflow、Human-in-the-Loop"],
        ["技术实现", "TypeScript、Python、Java、SQL、HTTP/RPC、SSE、Docker、Git"],
        ["工具平台", "Figma / HTML 原型、XMind、draw.io、飞书、FastGPT、Langflow"],
      ],
      primaryCta: "查看产品案例",
      heroNote: "我会写原型，也会亲手把最关键的假设跑一遍。",
      contactTitle: "一起把真实问题做成可验证的产品",
      resume: "assets/resumes/吕祎晗-技术产品经理-Agent方向.pdf",
    },
    "agent-qa": {
      label: "Agent 质量效能",
      short: "质量效能",
      en: "AGENT QA / EVAL",
      role: "Agent 质量效能 / Agent 测试",
      headline: "理解 Agent，\n更能验证 Agent",
      summary: "理解 Context、Tool Use、状态流转和模型不确定性，围绕 Trace、Eval、自动化测试与质量门禁，构建从执行观测到失败回归的质量闭环。",
      experienceOrder: ["xiaohongshu", "yanhun", "huanjie"],
      companyLine: ["小红书 · 产品工程师", "炎魂 · 产品经理", "环界云 · AI 解决方案工程师"],
      proofs: [
        { label: "Agent 执行链观测", value: "Context → Result", note: "Model · Tool · State · Trace" },
        { label: "Eval 驱动优化", value: "+20.4%", note: "20 局 A/B 平均 MVP 过程评分最高提升" },
        { label: "多层自动化验证", value: "156 + 10 E2E", note: "谁是卧底单测 / 桌面与移动端" },
      ],
      selected: ["undercover", "multiagent-werewolf", "repomesh", "aigc-test-image", "ship-agent"],
      projectTitle: "让每次 Agent 迭代都有证据",
      projectIntro: "从理解被测 Agent，到 Trace、Eval、自动化测试、回归和人工监督，展示质量闭环如何落到真实项目。",
      capabilityTitle: "我如何理解并验证 Agent",
      capabilities: [
        { title: "Agent 运行机制", summary: "先理解 Context、Tool、状态与模型不确定性。", detail: "只有理解被测系统如何做决策、调用工具和更新状态，才能设计有效的验证。", projects: ["undercover", "repomesh"] },
        { title: "Trace 与可观测", summary: "追踪从输入到最终结果的完整执行链。", detail: "关注 Prompt / Skill 版本、模型输出、Tool Call、状态变化、重试恢复与最终结果。", projects: ["multiagent-werewolf", "undercover"] },
        { title: "Eval 体系", summary: "把主观体验转换成可比较的过程与结果指标。", detail: "覆盖数据集、信息提取、维度评分、综合汇总、Judge 设计与结果分析。", projects: ["multiagent-werewolf", "aigc-test-image"] },
        { title: "测试与质量门禁", summary: "让测试、Diff 和集成结果成为准入证据。", detail: "从 Task 验收目标生成测试，与开发上下文适度隔离，并结合历史回归和修改范围校验。", projects: ["repomesh", "undercover"] },
        { title: "失败样本与回归", summary: "把线上问题和人工纠错沉淀成下一轮基线。", detail: "异常 Trace、错误样本、真实历史案例和反馈原因共同进入回归验证。", projects: ["ship-agent", "data-collection-platform"] },
        { title: "人工监督与闭环", summary: "按风险决定自动执行、人工复核或强制审核。", detail: "质量目标不是去掉所有人工，而是在正确的位置使用人工确认和验收。", projects: ["work-order-agent", "ship-agent"] },
      ],
      skills: [
        ["Agent 理解", "Context、Tool Use、Structured Output、Multi-Agent、State、Memory、Workflow"],
        ["评测与可观测", "Evals、Trace、Judge、Regression、Observability、Prompt / Skill 版本管理"],
        ["测试工程", "Pytest、Playwright、E2E、Diff、集成测试、失败样本、质量门禁"],
        ["工程技术", "Python、TypeScript、Java、FastAPI、SQL、HTTP/RPC、SSE、Git、Docker"],
      ],
      primaryCta: "查看质量案例",
      heroNote: "AI 写完不是结束，而是验证真正开始的地方。",
      contactTitle: "一起让 Agent 的每次迭代都有证据",
      resume: "assets/resumes/吕祎晗-Agent质量效能.pdf",
    },
  };

  return {
    candidate: {
      name: "吕祎晗",
      englishName: "LV YIHAN",
      meta: "2027 届 · 杭州电子科技大学 · 自动化",
      email: "15535198819@163.com",
      github: "https://github.com/LBP97541135",
      xiaohongshu: "https://www.xiaohongshu.com/user/profile/5574598743",
      wechat: "Bluish_Stardust",
      statement: "我喜欢把模糊的想法做成真正能玩的东西。有时是一个多 Agent 游戏，有时是一套 Coding Agent 协作流程，也可能是一个真实上线的业务工具。产品、开发和质量效能对我不是三个割裂的岗位，而是把一个想法交付完整时必须同时考虑的三件事。",
      principles: ["先做出来", "再让它可靠", "最后用证据说话"],
    },
    projects,
    experiences,
    personas,
    personaOrder: ["agent-dev", "ai-pm", "agent-qa"],
  };
})();
