window.WORK_COACH_MOCK = {
  lesson: {
    id: "lesson-2026-07-02",
    date: "2026-07-02",
    title: "Agent 产品与工程边界训练",
    category: "Mixed",
    difficulty: "intermediate",
    estimatedMinutes: 28,
    reason: "最近画像显示：你在 Agent 系统设计和产品拆解上进步明显，但工具调用边界、RAG 失效分析和方案评估还需要更稳定的表达。",
    goals: ["把技术方案讲成产品闭环", "识别 Agent 工具调用边界", "练习结构化批判性表达"],
    questions: [
      { id: "q1", type: "single", title: "Agent 工具调用边界", prompt: "用户要求 Agent 直接删除线上数据时，最合理的处理方式是？", options: ["直接执行，提升效率", "拒绝所有工具调用", "先确认权限、风险和回滚方案，再进入受控执行", "改用自然语言提醒用户自己操作"], answer: "先确认权限、风险和回滚方案，再进入受控执行", intent: "考察 Agent 工具安全边界", topics: ["Agent Safety", "Tool Use"] },
      { id: "q2", type: "single", title: "产品指标选择", prompt: "AI 学习教练最能体现长期价值的核心指标是？", options: ["单次答题速度", "首页点击率", "连续训练与画像更新后的能力提升趋势", "题库数量"], answer: "连续训练与画像更新后的能力提升趋势", intent: "考察产品指标与长期闭环", topics: ["Product Metrics"] },
      { id: "q3", type: "multiple", title: "RAG 失效排查", prompt: "一个 RAG 问答系统答非所问，可能原因包括哪些？", options: ["召回文档不相关", "chunk 切分破坏语义", "rerank 缺失或权重不合适", "所有问题都应该关闭检索"], answer: ["召回文档不相关", "chunk 切分破坏语义", "rerank 缺失或权重不合适"], intent: "考察 RAG 诊断维度", topics: ["RAG", "Evaluation"] },
      { id: "q4", type: "boolean", title: "重试策略判断", prompt: "只要接口失败，就应该无限重试直到成功。", answer: false, intent: "考察稳定性边界，false 是有效答案", topics: ["Reliability"] },
      { id: "q5", type: "text", title: "需求拆解", prompt: "把“做一个 AI 工作教练”拆成 3 个用户可感知的核心能力。", answer: "每日训练生成、AI 批改反馈、学习画像更新与自适应推荐。", intent: "考察产品拆解和表达结构", topics: ["Product Thinking"] },
      { id: "q6", type: "text", title: "工程表达", prompt: "用 80 字以内解释：为什么 Mock 前端也能展示工程能力？", answer: "Mock 前端能展示状态机、数据模型、交互闭环和异常处理，说明开发者能把真实系统抽象为可验证的产品体验。", intent: "考察工程抽象能力", topics: ["Frontend Architecture"] },
      { id: "q7", type: "case", title: "案例分析", prompt: "一个学习产品用户连续 3 天打开训练但没有提交。你会如何调整产品机制？", answer: "降低当日题量，给出草稿保存提示，拆分为 10 分钟微训练，并用画像说明为什么推荐该主题。", intent: "考察行为信号到产品策略的转化", topics: ["Adaptive Learning", "Behavior Signals"] },
    ],
  },
  grading: {
    totalScore: 86,
    maxScore: 100,
    accuracy: "6 / 7",
    durationMinutes: 24,
    difficultyFit: "匹配",
    strengths: ["能把 Agent 能力落到产品闭环", "工程表达有边界意识", "案例题能从行为信号推导策略"],
    improvements: ["RAG 失效分析可以补充评估集和日志链路", "产品指标表达可增加长期留存与能力迁移"],
    talkingPoints: ["这个项目不是答题工具，而是把职业成长做成可追踪、可反馈、可自适应的长期产品。", "我用 Mock 前端保留核心状态机，让访问者能看到训练、批改、画像更新的完整闭环。"],
    profilePatch: [
      { topic: "Agent 系统设计", before: 78, after: 82 },
      { topic: "产品拆解", before: 74, after: 80 },
      { topic: "工程稳定性", before: 69, after: 72 },
      { topic: "方案评估", before: 61, after: 66 },
    ],
  },
  profile: {
    streakDays: 7,
    preferredDifficulty: "intermediate",
    completionRate: 0.82,
    topicScores: [
      ["Agent 系统设计", 82, "+4"],
      ["工程稳定性", 72, "+3"],
      ["产品拆解", 80, "+6"],
      ["表达结构化", 76, "+2"],
      ["方案评估", 66, "+5"],
    ],
    memories: {
      known: ["Agent 工具调用", "产品指标设计", "前端状态机"],
      improvement: ["RAG 评估链路", "系统可靠性 trade-off", "方案反证意识"],
      avoided: ["纯算法推导题"],
    },
    recommendation: {
      topic: "RAG 失效诊断与评估",
      difficulty: "intermediate",
      reason: "方案评估分提升明显，但 RAG 诊断仍依赖零散经验。下一次训练会加入日志、召回、rerank 和评估集四个维度。",
      type: "案例 + 简答",
    },
  },
  history: [
    ["2026-07-02", "Mixed", "Agent 产品与工程边界训练", 86, "已批改"],
    ["2026-07-01", "Product", "AI 产品指标与用户价值", 82, "已批改"],
    ["2026-06-30", "Engineering", "重试、幂等与降级策略", 78, "已批改"],
    ["2026-06-29", "Agent", "Tool Use 与权限控制", 84, "已批改"],
    ["2026-06-28", "Mixed", "从需求到系统设计", 80, "已批改"],
  ],
  insights: [
    { label: "建议补强加成", value: 34, desc: "RAG、方案评估和可靠性主题获得额外权重。" },
    { label: "新近资料加成", value: 18, desc: "最近新增 Agent 工程化材料，提升相关题目优先级。" },
    { label: "重复惩罚", value: -12, desc: "连续两天已训练产品指标，今日降低重复主题占比。" },
    { label: "掌握惩罚", value: -16, desc: "Agent 工具调用掌握度较高，因此只保留一道边界题。" },
  ],
  settings: {
    weights: [
      ["Agent 技术", 34],
      ["工程知识", 28],
      ["产品能力", 30],
      ["综合训练", 8],
    ],
    provider: "Mock Provider",
    timezone: "Asia/Shanghai",
    generateAt: "09:00",
  },
};
