window.EVO_MOCK = {
  phases: [
    { id: "setup", label: "准备", title: "选择剧本与阵容", text: "系统根据剧本难度、玩家偏好和目标体验，推荐本局 Agent 阵容。" },
    { id: "intro", label: "介绍", title: "DM 开场", text: "雾港主理人介绍故事背景，并提示每个角色阅读自己的身份信息。" },
    { id: "script", label: "阅读", title: "剧本阅读", text: "玩家获得公开背景、私人目标和第一批可调查线索。" },
    { id: "investigation", label: "调查", title: "证物调查", text: "你可以调查场景、询问角色，并将证物出示给指定 Agent 或角色。" },
    { id: "deduction", label: "推理", title: "集中推理", text: "推理型 Agent 整合证物链，情绪型 Agent 提醒你谁在回避问题。" },
    { id: "reveal", label: "揭晓", title: "真相揭示", text: "系统展示真凶、动机、时间线和关键证据链。" },
    { id: "review", label: "复盘", title: "复盘进化", text: "Echo 生成复盘报告，并把可复用策略沉淀为 memory capsule。" },
  ],
  scripts: [
    {
      id: "rust-avenue",
      title: "锈铁大道",
      subtitle: "The Rusted Avenue",
      genre: "推理本",
      difficulty: "进阶",
      duration: "4-5 小时",
      players: "4-6 人",
      rating: 4.9,
      description: "停摆工厂、老旧宿舍与失踪名单被压在同一座锈色街区里，真相沿着管道缓慢回流。",
      tags: ["工业氛围", "时间线", "反转", "高复盘"],
      recommendedAgents: ["雾港主理人", "铁幕裁判", "白鸣陪玩"],
    },
    {
      id: "black-archive",
      title: "黑箱档案馆",
      subtitle: "Black Archive",
      genre: "情感本",
      difficulty: "入门",
      duration: "5-6 小时",
      players: "6-7 人",
      rating: 4.8,
      description: "七封旧信把陌生人带回同一个夜晚，档案馆里的每份记录都在隐瞒另一种真相。",
      tags: ["高沉浸", "情绪拉扯", "新手友好"],
      recommendedAgents: ["暮烛引导员", "回声", "南栀"],
    },
    {
      id: "mirror-parade",
      title: "镜面游行",
      subtitle: "Mirror Parade",
      genre: "阵营本",
      difficulty: "硬核",
      duration: "6 小时",
      players: "7-9 人",
      rating: 4.7,
      description: "面具、反光和舞台灯把每次发言切成碎片，所有阵营都在互相借力与拆台。",
      tags: ["阵营博弈", "控场", "高对抗"],
      recommendedAgents: ["铁幕裁判", "鸦青", "旧钟"],
    },
    {
      id: "salt-ward",
      title: "盐雾病房",
      subtitle: "Salt Ward",
      genre: "推理本",
      difficulty: "入门",
      duration: "3.5 小时",
      players: "5-6 人",
      rating: 4.6,
      description: "潮湿长廊与失效监控构成一场节奏温和、适合新手入门的推理练习。",
      tags: ["新手友好", "信息适中", "短时体验"],
      recommendedAgents: ["暮烛引导员", "雾港主理人", "回声"],
    },
    {
      id: "wolf-assembly",
      title: "狼群集会",
      subtitle: "Wolf Assembly",
      genre: "机制本",
      difficulty: "进阶",
      duration: "4.5 小时",
      players: "6-8 人",
      rating: 4.5,
      description: "围绕营地资源与夜巡制度展开博弈，角色推进与资源调度都需要精确计算。",
      tags: ["机制感", "资源调度", "夜谈博弈"],
      recommendedAgents: ["铁幕裁判", "燧石", "Echo"],
    },
    {
      id: "paper-cathedral",
      title: "纸穹教堂",
      subtitle: "Paper Cathedral",
      genre: "情感本",
      difficulty: "硬核",
      duration: "6-7 小时",
      players: "5-7 人",
      rating: 4.8,
      description: "一座纸做的教堂、一场无人承认的婚礼，以及每个人都不愿拆开的誓言。",
      tags: ["强叙事", "情绪爆发", "长线伏笔"],
      recommendedAgents: ["暮烛引导员", "Echo", "雾港主理人"],
    },
  ],
  dialogues: [
    { speaker: "雾港主理人", role: "DM Agent", text: "各位抵达锈铁大道时，主厂房的钟停在 23:17。警方记录却写着事故发生于 23:14。" },
    { speaker: "沈禾", role: "角色", text: "名单不是我改的。我只负责登记，钥匙一直挂在宿舍门后。" },
    { speaker: "铁幕裁判", role: "规则 Agent", text: "当前可追问方向：名单时间、钥匙归属、录音背景音。建议先确认时间线。" },
  ],
  evidences: [
    { id: "ev-1", type: "文件", title: "夜班名单", status: "公开", detail: "名单中沈禾的签名墨迹较新，23:14 到 23:17 之间有三分钟空白。" },
    { id: "ev-2", type: "录音", title: "车间噪声片段", status: "公开", detail: "录音中有三次蒸汽阀鸣响，对应的设备只会在二号管道开启时出现。" },
    { id: "ev-3", type: "物品", title: "备用钥匙", status: "待发现", detail: "钥匙齿面有新鲜铁锈，说明它近期被用于打开旧仓库。" },
    { id: "ev-4", type: "场景", title: "宿舍墙面划痕", status: "待发现", detail: "划痕高度与工具箱边缘吻合，墙后藏着一张被撕开的值班表。" },
  ],
  reasoning: [
    { id: "r1", evidence: "夜班名单", claim: "事故记录被延后了三分钟", confidence: 84, unlockPhase: 1 },
    { id: "r2", evidence: "车间噪声片段", claim: "录音地点并非主厂房，而是二号管道附近", confidence: 76, unlockPhase: 2 },
    { id: "r3", evidence: "备用钥匙", claim: "有人在事故后进入旧仓库处理痕迹", confidence: 68, unlockPhase: 3 },
    { id: "r4", evidence: "宿舍墙面划痕", claim: "被撕开的值班表才是动机链核心", confidence: 91, unlockPhase: 5 },
  ],
  suspects: [
    { name: "沈禾", motive: "隐瞒签名时间", timeline: 72, pressure: 64, status: "重点追问" },
    { name: "陆砚", motive: "掌握旧仓库钥匙", timeline: 86, pressure: 78, status: "高危嫌疑" },
    { name: "陈珀", motive: "维修记录缺页", timeline: 54, pressure: 42, status: "暂缓观察" },
  ],
  truthGraph: [
    ["时间异常", "夜班名单出现 23:14 到 23:17 的空白"],
    ["空间错位", "录音中的蒸汽阀声指向二号管道"],
    ["行动痕迹", "备用钥匙近期打开过旧仓库"],
    ["动机落点", "值班表被撕开，说明有人试图改写责任归属"],
  ],
  agents: [
    {
      id: "wugang",
      name: "雾港主理人",
      type: "DM",
      image: "./assets/agent-wugang.png",
      description: "负责开场叙事、节奏控制和线索投放，在玩家卡住时提供不剧透的方向提示。",
      tags: ["控场", "叙事", "低剧透提示"],
      stats: { reasoning: 82, empathy: 74, initiative: 88, memory: 80 },
      memory: "上局发现玩家偏好先搭时间线，再做角色动机排除。本局将优先提示时间相关证物。",
    },
    {
      id: "muzhu",
      name: "暮烛引导员",
      type: "Emotion",
      image: "./assets/agent-muzhu.png",
      description: "关注角色关系、情绪变化和叙事沉浸，适合情感本和新手陪跑。",
      tags: ["情绪洞察", "新手引导", "角色关系"],
      stats: { reasoning: 68, empathy: 94, initiative: 76, memory: 84 },
      memory: "玩家容易忽略沉默角色，暮烛会在关键节点提醒谁的情绪变化不自然。",
    },
    {
      id: "tiemu",
      name: "铁幕裁判",
      type: "Rule",
      image: "./assets/agent-tiemu.png",
      description: "负责规则边界、机制结算和高对抗场景控场，减少争议和跑偏。",
      tags: ["规则裁定", "机制结算", "高对抗"],
      stats: { reasoning: 88, empathy: 58, initiative: 90, memory: 72 },
      memory: "当玩家试图越过机制限制时，铁幕会给出替代行动，保证剧情不断流。",
    },
    {
      id: "echo",
      name: "Echo",
      type: "Review",
      image: "./assets/agent-echo.png",
      description: "将本局表现、证据使用和推理习惯整理成复盘报告，沉淀为下次可复用策略。",
      tags: ["复盘", "记忆胶囊", "成长建议"],
      stats: { reasoning: 86, empathy: 80, initiative: 70, memory: 96 },
      memory: "已记录玩家擅长追问客观证据，但在动机推理上需要更早建立反证路径。",
    },
  ],
  review: {
    score: 86,
    summary: "你发现了关键证物，但在动机链路上依赖了过多 DM 提示。Echo 已生成下一局训练建议。",
    moments: [
      ["23:14", "你首次发现名单时间与录音时间不一致。"],
      ["23:27", "你向沈禾出示夜班名单，她的回应出现明显停顿。"],
      ["23:41", "团队确认备用钥匙是打开旧仓库的关键物品。"],
      ["00:03", "真相揭晓：事故记录被人为延后了三分钟。"],
    ],
    capsules: [
      { title: "时间线优先", text: "当证据出现时间差，先建立事件表，再追问角色动机。" },
      { title: "沉默角色标记", text: "连续两轮不主动发言的角色，往往承担隐性信息或动机。" },
      { title: "证物出示节奏", text: "不要一次性抛出全部证据，先用弱证据观察角色反应。" },
    ],
  },
  profile: {
    traits: [
      ["偏好", "强推理 / 中等情绪 / 低恐怖"],
      ["节奏", "喜欢 20 分钟内出现第一个可推理矛盾"],
      ["协作", "常扮演整理信息与追问细节的人"],
      ["成长点", "动机链和反证意识需要提前建立"],
    ],
    recommendation: {
      title: "下一局推荐：镜面游行",
      text: "适合练习阵营信息拆解和反证路径。建议搭配铁幕裁判、鸦青和 Echo。",
    },
  },
};
