window.MPT_MOCK = {
  project: {
    id: "task_20260702_001",
    subject: "为什么年轻人需要建立长期主义",
    keywords: ["长期主义", "复利", "职业成长", "年轻人"],
    audience: "22-30 岁职场新人",
    style: "商业",
    language: "zh-CN",
    aspect: "9:16",
    resolution: "1080x1920",
    segmentDuration: 3,
    batchCount: 3,
    script: [
      { id: "s1", text: "很多年轻人焦虑，不是因为不努力，而是因为每次努力都被短期结果打断。", duration: 4, keywords: ["焦虑", "职场", "短期反馈"], materialId: "m1" },
      { id: "s2", text: "长期主义不是慢，而是把每天的选择放进同一个方向里，让能力产生复利。", duration: 5, keywords: ["复利", "方向", "积累"], materialId: "m2" },
      { id: "s3", text: "当你持续记录、复盘、迭代，时间就不再只是消耗，而会变成你的资产。", duration: 5, keywords: ["复盘", "记录", "资产"], materialId: "m3" },
      { id: "s4", text: "从今天开始，选一个值得坚持的能力，给它三个月，不要只给它三天。", duration: 5, keywords: ["行动", "坚持", "成长"], materialId: "m4" },
    ],
    voice: { name: "zh-CN-XiaoyiNeural", provider: "Edge", speed: "1.05x", emotion: "沉稳" },
    subtitle: { enabled: true, font: "HarmonyOS Sans", size: 42, color: "#FACC15", stroke: true, position: "bottom", provider: "whisper" },
    music: { mode: "指定音乐", track: "Warm Focus Beat", mood: "温暖", volume: 38 },
  },
  materials: [
    { id: "m1", title: "城市地铁通勤", source: "Mock Library", license: "可商用", color: "#334155" },
    { id: "m2", title: "桌面写计划", source: "Pexels", license: "可商用", color: "#1d4ed8" },
    { id: "m3", title: "数据曲线增长", source: "Mock Library", license: "本地", color: "#047857" },
    { id: "m4", title: "日出跑步剪影", source: "Pixabay", license: "可商用", color: "#b45309" },
    { id: "m5", title: "咖啡馆复盘", source: "本地素材", license: "本地", color: "#7c2d12" },
  ],
  pipeline: [
    { id: "topic", name: "主题解析", status: "pending", message: "提取主题、受众和风格" },
    { id: "script", name: "文案生成", status: "pending", message: "生成短视频脚本与分镜" },
    { id: "split", name: "分镜拆分", status: "pending", message: "拆分片段并估算时长" },
    { id: "material", name: "素材检索", status: "pending", message: "按关键词匹配视频素材" },
    { id: "voice", name: "配音生成", status: "pending", message: "生成 TTS 音轨" },
    { id: "subtitle", name: "字幕生成", status: "pending", message: "生成字幕并应用样式" },
    { id: "music", name: "音乐匹配", status: "pending", message: "匹配背景音乐并混音" },
    { id: "compose", name: "视频合成", status: "pending", message: "FFmpeg 合成候选视频" },
    { id: "quality", name: "质量检查", status: "pending", message: "检查字幕、节奏和素材相关度" },
  ],
  candidates: [
    { id: "a", title: "Candidate A · 稳定叙事版", style: "商业", duration: 19, aspect: "9:16", score: { script: 92, material: 88, voice: 86, subtitle: 94, rhythm: 89 } },
    { id: "b", title: "Candidate B · 快节奏增长版", style: "鸡汤", duration: 17, aspect: "9:16", score: { script: 84, material: 91, voice: 82, subtitle: 88, rhythm: 95 } },
    { id: "c", title: "Candidate C · 温暖故事版", style: "故事", duration: 23, aspect: "9:16", score: { script: 89, material: 84, voice: 92, subtitle: 86, rhythm: 82 } },
  ],
  tasks: [
    ["task_20260702_001", "为什么年轻人需要建立长期主义", "已完成", 3, "20:18", "42s", 100],
    ["task_20260701_018", "普通人如何做副业复盘", "已完成", 2, "昨天", "36s", 100],
    ["task_20260701_006", "AI 工具如何提升学习效率", "生成中", 3, "昨天", "18s", 62],
    ["draft_20260630_011", "职场新人沟通避坑", "草稿", 1, "06-30", "-", 0],
  ],
  gallery: [
    { id: "v1", title: "为什么年轻人需要建立长期主义", aspect: "9:16", duration: "00:19", createdAt: "2026-07-02", model: "gpt-4.1 + Edge TTS", tags: ["成长", "职场", "商业"] },
    { id: "v2", title: "普通人如何做副业复盘", aspect: "16:9", duration: "00:42", createdAt: "2026-07-01", model: "Moonshot + Azure TTS", tags: ["副业", "复盘"] },
    { id: "v3", title: "AI 工具如何提升学习效率", aspect: "9:16", duration: "00:31", createdAt: "2026-07-01", model: "DeepSeek + Mock Voice", tags: ["AI", "学习"] },
  ],
  providers: {
    llm: ["OpenAI", "Moonshot", "Azure", "通义千问", "Google Gemini", "Ollama", "DeepSeek", "Mock Provider"],
    material: ["Pexels", "Pixabay", "本地素材", "Mock Library"],
    tts: ["Edge", "Azure", "OpenAI TTS", "Mock Voice"],
    subtitle: ["whisper", "edge", "none"],
    deps: ["FFmpeg", "ImageMagick", "Whisper 模型", "字体资源", "背景音乐资源"],
  },
};
